verbose: True

mqtt:
  broker: test.mosquitto.org
  port: 1883
delay:
  max_idle_time: 600 
logfile: /tmp/rpisensors.log

# s1, s2 are names never used. GPIO and type are important, see README.
# PIR and Reed switches works in the same way.
sensors:
  sensor:
    gpio: -1      # Negative to not crash with actual GPIO sensors
    type: cputemp # Will fetch rpi cpu temp, just for testing
    check_every: 2
  s1:
    gpio: 17
    type: ds18b20
    delay: 60
    offset: 0 # Adjust temperature if needed
  s2:
    gpio: 18
    type: pir
    delay: 4
  s3:
    gpio: 19
    type: reed
  s4:
    gpio: 0 # Not used, but should be unique
    type: xloborg
    delay: 30
    offset: -1 # Too zero out the base level
  s5:
    gpio: 4
    type: digital
    invert: True
