verbose: True
# Use the ACT LED of the rpi to blink on updates sent
actled: True

mqtt:
  broker: test.mosquitto.org
  port: 1883
delay:
  check_every: 3
  max_idle_time: 600 

# s1, s2 are names never used. GPIO and type are important, see README.
sensors:
  s1:
    gpio: 17
    type: ds18b20
  s2:
    gpio: 18
    type: pir
  s3:
    gpio: 0
    type: xloborg
